"""Generate compilable GTest skeleton files from test plans.
从测试计划生成可编译的 GTest 骨架/智能用例文件。
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from sdk_forge.codegen import (
    render_assertion,
    render_class_body,
    render_enum_body,
    render_fixture_block,
    render_test_p_block,
)
from sdk_forge.plan import suggest_test_plan_impl


def _safe_test_suite(symbol: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]", "", symbol)
    if not cleaned:
        return "ForgeTest"
    return cleaned[0].upper() + cleaned[1:] if cleaned[0].islower() else cleaned


def _safe_scenario(name: str) -> str:
    parts = re.split(r"[_\s-]+", name.strip())
    return "".join(p.capitalize() for p in parts if p) or "Case"


def _header_include(header_file: str) -> str:
    if not header_file:
        return ""
    name = Path(header_file).name
    if "/" in header_file.replace("\\", "/"):
        return f'#include "{header_file.replace(chr(92), "/")}"'
    return f'#include "{name}"'


def _function_test_body(
    symbol: str,
    scenario: dict[str, Any],
    target: dict[str, Any],
    fidelity: str,
) -> str:
    return render_assertion(symbol, scenario, target, fidelity=fidelity)


def _render_function_target(target: dict[str, Any], fidelity: str = "smart") -> str:
    symbol = target.get("symbol", "api")
    suite = _safe_test_suite(symbol)
    header = _header_include(target.get("file", ""))
    lines = [
        "// Generated by SDK Test Forge — edit AGENT/TODO sections for complex APIs.",
        "#include <gtest/gtest.h>",
    ]
    if target.get("use_test_p"):
        lines.append("#include <string>")
    if header:
        lines.append(header)
    if target.get("conditional"):
        args = target.get("suggested_compile_args") or ["-DFEATURE_ENABLED"]
        lines.append(f"// NOTE: conditional API — add compile args: {', '.join(args)}")
    lines.append("")
    for scenario in target.get("scenarios") or []:
        case = _safe_scenario(str(scenario.get("name", "Case")))
        lines.append(f"TEST({suite}, {case}) {{")
        lines.append(_function_test_body(symbol, scenario, target, fidelity))
        lines.append("}")
        lines.append("")
    if target.get("use_test_p") and fidelity == "smart":
        lines.append(render_test_p_block(target, suite))
    return "\n".join(lines).rstrip() + "\n"


def _render_class_target(target: dict[str, Any], fidelity: str = "smart") -> str:
    symbol = target.get("symbol", "Type")
    suite = _safe_test_suite(symbol)
    header = _header_include(target.get("file", ""))
    lines = [
        "// Generated by SDK Test Forge — edit AGENT/TODO sections for complex APIs.",
        "#include <gtest/gtest.h>",
    ]
    if target.get("needs_mock"):
        lines.append("#include <gmock/gmock.h>")
        lines.append(f'#include "mock_{symbol}.hpp"')
        lines.append(f"// Run generate_mocks for {symbol} if mock file is missing.")
    elif header:
        lines.append(header)
    if target.get("conditional"):
        args = target.get("suggested_compile_args") or ["-DFEATURE_ENABLED"]
        lines.append(f"// NOTE: conditional type — add compile args: {', '.join(args)}")
    lines.append("")
    for scenario in target.get("scenarios") or []:
        case = _safe_scenario(str(scenario.get("name", "Case")))
        lines.append(f"TEST({suite}, {case}) {{")
        lines.append(render_class_body(symbol, scenario, target, fidelity=fidelity))
        lines.append("}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _render_enum_target(target: dict[str, Any], fidelity: str = "smart") -> str:
    symbol = target.get("symbol", "Enum")
    suite = _safe_test_suite(symbol)
    header = _header_include(target.get("file", ""))
    lines = [
        "// Generated by SDK Test Forge — enum test cases.",
        "#include <gtest/gtest.h>",
    ]
    if header:
        lines.append(header)
    lines.append("")
    for scenario in target.get("scenarios") or []:
        case = _safe_scenario(str(scenario.get("name", "Case")))
        lines.append(f"TEST({suite}, {case}) {{")
        lines.append(render_enum_body(symbol, scenario, target, fidelity=fidelity))
        lines.append("}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _render_file_content(
    targets: list[dict[str, Any]],
    fidelity: str,
    include_fixture: bool = False,
) -> str:
    if not targets:
        return ""
    primary = targets[0]
    kind = primary.get("kind", "function")
    if kind == "enum":
        return _render_enum_target(primary, fidelity)
    if kind in ("class", "struct"):
        return _render_class_target(primary, fidelity)
    content = _render_function_target(primary, fidelity)
    if include_fixture and len(targets) > 1:
        suite = _safe_test_suite(primary.get("symbol", "Api"))
        fixture = render_fixture_block(targets, suite)
        if fixture:
            content = content.rstrip() + "\n\n" + fixture
    return content


def generate_test_skeleton_impl(
    plan_json: str | dict[str, Any] | None = None,
    output_dir: str = "",
    sdk_root: str = "",
    project_name: str = "sdk_tests",
    overwrite: bool | str = False,
    fidelity: str = "smart",
    group_by_header: bool | str = False,
) -> dict[str, Any]:
    from sdk_forge.util import parse_bool

    if plan_json:
        if isinstance(plan_json, str):
            try:
                plan = json.loads(plan_json)
            except json.JSONDecodeError as exc:
                return {"status": "error", "error": f"Invalid plan JSON: {exc}"}
        else:
            plan = plan_json
    elif sdk_root:
        plan = suggest_test_plan_impl(sdk_root=sdk_root)
    else:
        return {"status": "error", "error": "Provide plan_json or sdk_root"}

    if plan.get("status") == "error":
        return plan

    fid = fidelity if fidelity in ("smart", "skeleton") else "smart"
    out = Path(output_dir or "tests")
    out.mkdir(parents=True, exist_ok=True)
    do_overwrite = parse_bool(overwrite, default=False)
    do_group = parse_bool(group_by_header, default=False)

    written: list[str] = []
    skipped: list[str] = []
    targets = plan.get("targets") or []

    if do_group:
        by_file: dict[str, list[dict[str, Any]]] = {}
        for target in targets:
            key = target.get("file") or "misc"
            by_file.setdefault(key, []).append(target)
        for file_key, group in by_file.items():
            safe = re.sub(r"[^A-Za-z0-9_]", "_", Path(file_key).stem).strip("_").lower() or "api"
            filename = out / f"{safe}_test.cpp"
            if filename.exists() and not do_overwrite:
                skipped.append(str(filename))
                continue
            content = _render_file_content(group, fid, include_fixture=True)
            filename.write_text(content, encoding="utf-8")
            written.append(str(filename.resolve()))
    else:
        for target in targets:
            symbol = target.get("symbol") or project_name
            safe = re.sub(r"[^A-Za-z0-9_]", "_", symbol).strip("_").lower() or "api"
            filename = out / f"{safe}_test.cpp"
            if filename.exists() and not do_overwrite:
                skipped.append(str(filename))
                continue
            kind = target.get("kind", "function")
            if kind == "enum":
                content = _render_enum_target(target, fid)
            elif kind in ("class", "struct"):
                content = _render_class_target(target, fid)
            else:
                content = _render_function_target(target, fid)
            filename.write_text(content, encoding="utf-8")
            written.append(str(filename.resolve()))

    return {
        "status": "ok",
        "output_dir": str(out.resolve()),
        "files_written": written,
        "files_skipped": skipped,
        "target_count": len(targets),
        "plan_summary": plan.get("summary"),
        "fidelity": fid,
    }
