"""Generate compilable GTest skeleton files from test plans."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from sdk_forge.plan import suggest_test_plan_impl


def _safe_test_suite(symbol: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]", "", symbol)
    if not cleaned:
        return "ForgeTest"
    return cleaned[0].upper() + cleaned[1:] if cleaned[0].islower() else cleaned


def _safe_scenario(name: str) -> str:
    parts = re.split(r"[_\s-]+", name.strip())
    return "".join(p.capitalize() for p in parts if p) or "Case"


def _header_include(header_file: str) -> str:
    if not header_file:
        return ""
    return f'#include "{Path(header_file).name}"'


def _function_test_body(symbol: str, scenario: dict[str, Any], return_type: str) -> str:
    desc = scenario.get("description", scenario.get("name", ""))
    name = scenario.get("name", "case")
    if name == "normal":
        return f"""    // TODO: {desc}
    // EXPECT_*({symbol}(...), ...);"""
    if name == "error":
        return f"""    // TODO: {desc}
    // EXPECT_* failure path for {symbol}"""
    return f"""    // TODO: {desc}
    EXPECT_TRUE(true);  // replace with real assertion for {symbol}"""


def _render_function_target(target: dict[str, Any]) -> str:
    symbol = target.get("symbol", "api")
    suite = _safe_test_suite(symbol)
    header = _header_include(target.get("file", ""))
    lines = [
        "// Generated by SDK Test Forge — edit TODO sections before relying on assertions.",
        "#include <gtest/gtest.h>",
    ]
    if header:
        lines.append(header)
    if target.get("conditional"):
        args = target.get("suggested_compile_args") or ["-DFEATURE_ENABLED"]
        lines.append(f"// NOTE: conditional API — add compile args: {', '.join(args)}")
    lines.append("")
    for scenario in target.get("scenarios") or []:
        case = _safe_scenario(str(scenario.get("name", "Case")))
        lines.append(f"TEST({suite}, {case}) {{")
        lines.append(_function_test_body(symbol, scenario, target.get("return_type", "")))
        lines.append("}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _render_class_target(target: dict[str, Any]) -> str:
    symbol = target.get("symbol", "Type")
    suite = _safe_test_suite(symbol)
    header = _header_include(target.get("file", ""))
    lines = [
        "// Generated by SDK Test Forge — edit TODO sections before relying on assertions.",
        "#include <gtest/gtest.h>",
    ]
    if target.get("needs_mock"):
        lines.append(f'#include "mock_{symbol}.hpp"')
        lines.append(f"// Run generate_mocks for {symbol} if mock file is missing.")
    elif header:
        lines.append(header)
    if target.get("conditional"):
        args = target.get("suggested_compile_args") or ["-DFEATURE_ENABLED"]
        lines.append(f"// NOTE: conditional type — add compile args: {', '.join(args)}")
    lines.append("")
    for scenario in target.get("scenarios") or []:
        case = _safe_scenario(str(scenario.get("name", "Case")))
        lines.append(f"TEST({suite}, {case}) {{")
        desc = scenario.get("description", "")
        if target.get("needs_mock") and scenario.get("name") == "mock":
            lines.append(f"    // TODO: {desc}")
            lines.append(f"    // Mock{symbol} mock; EXPECT_CALL(mock, ...);")
        elif scenario.get("name") == "construction":
            lines.append(f"    // TODO: {desc}")
            lines.append(f"    // {symbol} obj; /* construct and verify */")
        else:
            lines.append(f"    // TODO: {desc}")
            methods = target.get("methods") or []
            if methods:
                lines.append(f"    // exercise: {', '.join(methods[:3])}")
            lines.append("    EXPECT_TRUE(true);")
        lines.append("}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def generate_test_skeleton_impl(
    plan_json: str | dict[str, Any] | None = None,
    output_dir: str = "",
    sdk_root: str = "",
    project_name: str = "sdk_tests",
    overwrite: bool | str = False,
) -> dict[str, Any]:
    from sdk_forge.util import parse_bool

    if plan_json:
        if isinstance(plan_json, str):
            try:
                plan = json.loads(plan_json)
            except json.JSONDecodeError as exc:
                return {"status": "error", "error": f"Invalid plan JSON: {exc}"}
        else:
            plan = plan_json
    elif sdk_root:
        plan = suggest_test_plan_impl(sdk_root=sdk_root)
    else:
        return {"status": "error", "error": "Provide plan_json or sdk_root"}

    if plan.get("status") == "error":
        return plan

    out = Path(output_dir or "tests")
    out.mkdir(parents=True, exist_ok=True)
    do_overwrite = parse_bool(overwrite, default=False)

    written: list[str] = []
    skipped: list[str] = []

    for target in plan.get("targets") or []:
        symbol = target.get("symbol") or project_name
        safe = re.sub(r"[^A-Za-z0-9_]", "_", symbol).strip("_").lower() or "api"
        filename = out / f"{safe}_test.cpp"
        if filename.exists() and not do_overwrite:
            skipped.append(str(filename))
            continue
        if target.get("kind") in ("class", "struct"):
            content = _render_class_target(target)
        else:
            content = _render_function_target(target)
        filename.write_text(content, encoding="utf-8")
        written.append(str(filename.resolve()))

    return {
        "status": "ok",
        "output_dir": str(out.resolve()),
        "files_written": written,
        "files_skipped": skipped,
        "target_count": len(plan.get("targets") or []),
        "plan_summary": plan.get("summary"),
    }
